config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  resources :projects do
    resources :tasks
  end
  devise_for :users
  root 'welcome#index'
  

end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :project
  belongs_to :user
  
  enum status: { initial: 1, in_progress: 2, done: 3 }
 
  validates :name, :status, :description, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :set_project

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = current_user.role?('developer') ? current_user.tasks.where(:project_id => @project.id) : @project.tasks
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @project = Project.find(params[:project_id])
    @task = @project.tasks.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create  
    @task = @project.tasks.new(task_params)
    respond_to do |format|
      if @task.save
        format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    respond_to do |format|
      if @task.update(task_params)
        format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    @task.destroy
    respond_to do |format|
      format.html { redirect_to project_tasks_path(@project), notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task
      @task = Task.find(params[:id])
    end

    # Set project
    def set_project
      @project = Project.find(params[:project_id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def task_params
      params.require(:task).permit(:name, :description, :project_id, :status, :user_id)
    end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.haml
= form_for [@project, @task] do |f|
  - if @task.errors.any?
    #error_explanation
      %h2= "#{pluralize(@task.errors.count, "error")} prohibited this task from being saved:"
      %ul
        - @task.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :status
    = f.select(:status, options_for_select([["Initial", "initial"], ["In Progress", "in_progress"], ["Done", "done"]], selected: @task.status))
  - if !current_user.role?('developer')
    .field
      = f.label :user_id
      = f.select(:user_id, options_for_select(User.developers.map{|m| [m.email, m.id]}, selected: @task.user.try(:id)),{include_blank: true})
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/tasks/edit.html.haml
%h1 Editing task

= render 'form'

= link_to 'Back', project_tasks_path(@project), class: "btn"

app/views/tasks/index.html.haml
%h1= @project.name
%br
%table
  %thead
    %tr
      %th Task Name
      %th Description
      %th Project
      %th Status
      %th User
      %th
      %th
      %th

  %tbody
    - @tasks.each do |task|
      %tr
        %td= task.name
        %td= task.description
        %td= task.project.name
        %td= task.status
        %td= task.user.try(:email)
        %td= link_to 'Show', project_task_path(@project, task)
        %td= link_to 'Edit', edit_project_task_path(@project, task)
        %td= link_to 'Destroy', project_task_path(@project, task), :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'Back', projects_path, class: "btn"

- if can? :manage, Task
  = link_to 'New Task',  new_project_task_path(@project), class: "btn btn-success"

app/views/tasks/new.html.haml
%h1 New task

= render 'form'

= link_to 'Back', project_tasks_path(@project), class: "btn"

app/views/tasks/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @task.name
%p
  %b Description:
  = @task.description
%p
  %b Project:
  = @task.project.name
%p
  %b Status:
  = @task.status
%p
  %b User:
  = @task.user.try(:email)

= link_to 'Edit', edit_project_task_path(@project, @task), class: "btn"
\|
= link_to 'Back', project_tasks_path(@project), class: "btn"