config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  resources :projects do
    resources :tasks
  end
  devise_for :users
  root 'welcome#index'
  

end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :tasks
  validates :name, :description, presence: true

  def status(type)
    tasks.where(status: type).count
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = current_user.role?('developer') ? current_user.projects : Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :description, :client, :active)
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    #error_explanation
      %h2= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      %ul
        - @project.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :client
    = f.text_field :client
  .field
    = f.label :active
    = f.check_box :active
  .actions
    = f.submit 'Save', class: "btn btn-success"

app/views/projects/edit.html.haml
%h1 Editing project

= render 'form'

= link_to 'Show', @project, class: "btn"
\|
= link_to 'Back', projects_path, class: "btn"

app/views/projects/index.html.haml
%h1 Listing projects
%br
%table
  %thead
    %tr
      %th Name
      %th Description
      %th Client
      %th Active
      %th{colspan: 3} Actions
      %th Tasks

  %tbody
    - @projects.each do |project|
      %tr
        %td= project.name
        %td= project.description
        %td= project.client
        %td= project.active
        %td= link_to 'Show', project
        %td= link_to 'Edit', edit_project_path(project)
        %td= link_to 'Destroy', project, :method => :delete, :data => {:confirm => 'Are you sure?'}
        %td= link_to 'View all tasks', project_tasks_path(project)

- if can? :manage, Project
  %h4
    = link_to 'Create New Project', new_project_path, class: "btn btn-success"

app/views/projects/new.html.haml
%h1 New project

= render 'form'

= link_to 'Back', projects_path, :class => "btn"

app/views/projects/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @project.name
%p
  %b Description:
  = @project.description
%p
  %b Client:
  = @project.client
%p
  %b Active:
  = @project.active

= link_to 'Edit', edit_project_path(@project), :class => "btn"
|
= link_to 'Back', projects_path, :class => "btn"

%br
%br
= link_to "Create Task", new_project_task_path(@project.id), :class => "btn btn-success"