config/routes.rb
Rails.application.routes.draw do
  
  resources :members
  resources :projects do
    resources :tasks
  end
  devise_for :users
  root 'welcome#index'
  

end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  # GET /members
  # GET /members.json
  def index
    @members = User.all
  end

  # GET /members/1
  # GET /members/1.json
  def show
  end

  # GET /members/new
  def new
    @member = User.new
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  # def create
  #   @member = User.new(member_params)

  #   respond_to do |format|
  #     if @user.save
  #       format.html { redirect_to @member, notice: 'Member was successfully created.' }
  #       format.json { render :show, status: :created, location: @member }
  #     else
  #       format.html { render :new }
  #       format.json { render json: @user.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to members_url, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_member
      @member = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def member_params
      params.require(:user).permit(:email, :role)
    end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
= simple_form_for(@member, :url => member_path(@member)) do |f|
  = f.error_notification

  .form-inputs
    = f.input :email
    %div
      Role
    = f.select :role, options_for_select([["Developer", "developer"],["Manager", "manager"]])
  .form-actions
    = f.button :submit, class: "btn btn-success"

app/views/members/edit.html.haml
%h1 Editing member

= render 'form'

= link_to 'Back', :back, class: "btn"

app/views/members/index.html.haml
%h1 Listing members

%table
  %thead
    %tr
      %th Email
      %th Role
      %th Action

  %tbody
    - @members.each do |member|
      %tr
        %td= member.email
        %td= member.role
        %td= link_to 'Edit', edit_member_path(member)

app/views/members/new.html.haml
%h1 New member

= render 'form'

= link_to 'Back', members_path

app/views/members/show.html.haml
%p#notice= notice


= link_to 'Edit', edit_member_path(@member)
\|
= link_to 'Back', members_path